from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.ai.models.core import AIRequest, ChatMessage
from app.ai.prompts.library import prompt_library
from app.ai.providers.base import AIProvider
from app.ai.providers.factory import get_ai_provider
from app.ai.services.demo_jobs import DemoJob, DemoJobManager
from app.ai.services.deployment import VercelDeploymentAdapter
from app.ai.services.templates import TemplateEngine
from app.core.config import get_settings
from app.db.session import SessionLocal
from app.models.demo import Demo
from app.services.businesses import get_business_or_404


class DemoWebsiteGenerator:
    """Generate, build, deploy, and store demo websites."""

    def __init__(
        self,
        db: Session,
        provider: AIProvider | None = None,
        templates: TemplateEngine | None = None,
    ) -> None:
        self._db = db
        self._settings = get_settings()
        self._provider = provider or get_ai_provider(self._settings)
        self._templates = templates or TemplateEngine()
        self._deployment = VercelDeploymentAdapter(self._settings)

    async def generate(self, *, business_id: int, template: str) -> Demo:
        """Generate and deploy a demo website for a business."""
        business = get_business_or_404(self._db, business_id)
        generated = await self._content_for_demo(business_id, template)
        config = self._templates.config_for(template, business, generated)
        html = self._templates.render(config)
        version = self._next_version(business_id)
        output_dir = Path("generated") / "demos" / str(business_id) / f"v{version}"
        output_dir.mkdir(parents=True, exist_ok=True)
        html_path = output_dir / "index.html"
        html_path.write_text(html, encoding="utf-8")
        deployment = await self._deployment.deploy(
            project_name=f"leadforge-{business_id}-{template}-v{version}",
            html_path=html_path,
        )
        demo = Demo(
            business_id=business_id,
            demo_url=deployment.url,
            deployment_status=deployment.status,
            deployment_date=datetime.now(UTC),
            revision_history=json.dumps([{"version": version, "template": template}]),
            template_used=template,
            version=version,
            notes="Generated by LeadForge AI Demo Website Generator.",
        )
        self._db.add(demo)
        self._db.commit()
        self._db.refresh(demo)
        return demo

    async def _content_for_demo(self, business_id: int, template: str) -> dict[str, object]:
        business = get_business_or_404(self._db, business_id)
        prompt = prompt_library.list_prompts()["demo_content"]
        response = await self._provider.generate(
            AIRequest(
                messages=[
                    ChatMessage(role="system", content=prompt),
                    ChatMessage(
                        role="user",
                        content=(
                            f"Business: {business.business_name}\n"
                            f"Category: {business.category or template}\n"
                            f"City: {business.city}\nPhone: {business.phone_number}\n"
                            "Return JSON with heroHeadline, about, services array, faq array, "
                            "seoTitle, seoDescription, metaKeywords, cta, testimonials array. "
                            "Testimonials must be marked as sample content for client review."
                        ),
                    ),
                ],
                model=self._settings.ai_model,
                temperature=self._settings.ai_temperature,
                max_tokens=self._settings.ai_max_tokens,
            )
        )
        try:
            parsed = json.loads(response.content)
            return parsed if isinstance(parsed, dict) else {}
        except json.JSONDecodeError:
            return {
                "heroHeadline": f"A professional online presence for {business.business_name}",
                "about": response.content,
                "services": [business.category or template.replace("_", " ").title()],
                "faq": ["Sample FAQ content for client review."],
                "cta": "Contact us today",
                "testimonials": ["Sample testimonial for client review."],
            }

    def _next_version(self, business_id: int) -> int:
        latest = self._db.scalar(
            select(Demo.version)
            .where(Demo.business_id == business_id)
            .order_by(Demo.version.desc())
            .limit(1)
        )
        return (latest or 0) + 1


async def run_demo_generation_job(job: DemoJob, manager: DemoJobManager, *, template: str) -> None:
    """Run demo generation as a background task."""
    manager.update(job.job_id, status="RUNNING", current_task="Generating content", progress=20)
    db = SessionLocal()
    try:
        generator = DemoWebsiteGenerator(db)
        manager.update(job.job_id, current_task="Building website", progress=55)
        demo = await generator.generate(business_id=job.business_id, template=template)
        manager.update(
            job.job_id,
            status="COMPLETED",
            current_task="Completed",
            progress=100,
            demo_url=demo.demo_url,
            completed_at=datetime.now(UTC),
        )
    except Exception as exc:
        manager.update(
            job.job_id,
            status="FAILED",
            current_task="Failed",
            errors=[str(exc)],
            completed_at=datetime.now(UTC),
        )
    finally:
        db.close()
